spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mydebts
    username: postgres
    password: admin123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

server:
  port: 8080

jwt:
  secret: mysecretkey123
  expiration: 3600000 # 1 hora em milissegundos
